### ISSUE TITLE
Message will not be sent because the WebSocket session has been closed

### ISSUE THREAD

**Issue by gbajson** [boschkundendienst/guacamole-docker-compose#57]
Hi,
I experience issue with VNC connection from  `guacamole_compose`.

I can manually connect to VNC server from within `guacamole_compose` container, but I see the errors in logs:

**Investigation:**
```
$ docker cp ~/Downloads/busybox guacamole_compose:/tmp
$ docker exec -ti guacamole_compose /bin/bash
guacamole@43f04b98ba7f:/opt/guacamole$ /tmp/busybox nc 10.144.107.99 5900
RFB 003.008
```

**Logs:**
```
Exception in thread "Thread-131" java.lang.IllegalStateException: Message will not be sent because the WebSocket session has been closed
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.writeMessagePart(WsRemoteEndpointImplBase.java:442)
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:314)
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:254)
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendString(WsRemoteEndpointImplBase.java:195)
        at org.apache.tomcat.websocket.WsRemoteEndpointBasic.sendText(WsRemoteEndpointBasic.java:37)
        at org.apache.guacamole.websocket.GuacamoleWebSocketTunnelEndpoint.sendInstruction(GuacamoleWebSocketTunnelEndpoint.java:152)
        at org.apache.guacamole.websocket.GuacamoleWebSocketTunnelEndpoint.access$200(GuacamoleWebSocketTunnelEndpoint.java:53)
        at org.apache.guacamole.websocket.GuacamoleWebSocketTunnelEndpoint$2.run(GuacamoleWebSocketTunnelEndpoint.java:253)
```

I use Ubuntu 22.04 with standard docker-ce network configuration.

**Logging config**
I changed the following logging from INFO to FINE - but I don't see any more logs:
```
guacamole@43f04b98ba7f:~/tomcat/conf$ tail -1 /home/guacamole/tomcat/conf/logging.properties
org.apache.tomcat.websocket.level = FINE
```

Here is the sniffed traffic for this connection (export from [Wireshark](https://i.imgur.com/Zavd0bj.png) ):

```
GET /guacamole/websocket-tunnel?token=158DBAC70E0D8C5B2601CF5D40899A472E15311B4C8D88423677973E0BD050D1&GUAC_DATA_SOURCE=postgresql&GUAC_ID=1&GUAC_TYPE=c&GUAC_WIDTH=2553&GUAC_HEIGHT=1296&GUAC_DPI=96&GUAC_TIMEZONE=Europe%2FWarsaw&GUAC_AUDIO=audio%2FL8&GUAC_AUDIO=audio%2FL16&GUAC_IMAGE=image%2Fjpeg&GUAC_IMAGE=image%2Fpng&GUAC_IMAGE=image%2Fwebp HTTP/1.1
X-Forwarded-For: 172.20.0.1
Upgrade: websocket
Connection: keep-alive, Upgrade
Host: guacamole:8080
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Sec-WebSocket-Version: 13
Origin: https://localhost:8443
Sec-WebSocket-Protocol: guacamole
Sec-WebSocket-Extensions: permessage-deflate
Sec-WebSocket-Key: h/Mqm1gvuOYPyaPypNj4uw==
Cookie: _pk_id.1.1fff=191f55e5f44d40f3.1658155265.
Sec-Fetch-Dest: websocket
Sec-Fetch-Mode: websocket
Sec-Fetch-Site: same-origin
Pragma: no-cache
Cache-Control: no-cache

HTTP/1.1 101 
Upgrade: websocket
Connection: upgrade, keep-alive
Sec-WebSocket-Accept: fnf9hKAyahrwwdTLtTJT8OphNak=
Sec-WebSocket-Protocol: guacamole
Sec-WebSocket-Extensions: permessage-deflate
Date: Sat, 25 Feb 2023 21:11:33 GMT
Keep-Alive: timeout=20

.+...
. ..............l...tRzp..2..%+L..(t$...%2.K-*./.1..sL./*IM.S.NMU..O/...gjhi
......@....:.J.<.O
.u.@..........
```

Regards,
Grzegorz

**Comment by gbajson** [comment]
I also dumped traffic in `guacd_compose` container and learnt that there is a [malformed VNC packet](https://i.imgur.com/roHzEbh.png).
I am trying to connect to VNC provided by [docker-selenium](https://github.com/SeleniumHQ/docker-selenium). I have no problem with connection using e.g. Remmina.

**Comment by gbajson** [comment]
This might be [the following issue](https://issues.apache.org/jira/projects/GUACAMOLE/issues/GUACAMOLE-1741?filter=allopenissues).
